### PR TITLE
correct ic property

### PR DESCRIPTION
**Pull request by orgua**

### CODE REVIEW

**Comment by drom** [comment]
@orgua thanks for the corrections ;)

**Comment by drom** [comment]
@orgua the PCB in the repo is not completed yet. I can commit better version if you are interested.

**Comment by orgua** [comment]
no thanks, i will choose different ICs and packages. your project was a good orientation. and i still struggle with the fact to have a seconds rf signal source with 10-20 dBm on the same board :-)

**Comment by drom** [comment]
@orgua I power off WiFi while perform measurements.

**Pull request merged**
